Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -71,8 +71,16 @@ runs:
         shell: bash
         run: |-
           echo "${{ inputs.github_repository }}"
-          response=$(curl -s -X GET "https://github-integration.andreani.com/api/v1/org/${{ inputs.github_repository_owner }}/repository/${{ inputs.github_repository }}")
-          echo "Response: $response"
+          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" "https://github-integration.andreani.com/api/v1/org/${{ inputs.github_repository_owner }}/repository/${{ inputs.github_repository }}")
+          if [ "$status_code" -eq 200 ]; then
+            echo "Successful request"
+          elif [ "$status_code" -eq 404 ]; then
+            echo "Error: Not found"
+            exit 1
+          else
+            echo "Error: Status code $status_code"
+            exit 1
+          fi
       - name: "Continuos Integration .NET"
         if: ${{ inputs.workflow == '.NET' }}
         uses: infrastructure-services/continuos-integration@net
