Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -67,22 +67,22 @@ inputs:
 runs:
   using: "composite"
   steps: 
-      - name: "Consulta al endpoint"
-        shell: bash
-        run: |-
-          echo "${{ inputs.github_repository }}"
-          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" --location --head "https://github-integration.andreani.com/api/v1/org/${{ inputs.github_repository_owner }}/repository/${{ inputs.github_repository }}")
-          if [ "$status_code" -eq 200 ]; then
-            echo "Successful request"
-          elif [ "$status_code" -eq 404 ]; then
-            echo "Error: Not found"
-            exit 1
-          else
-            echo "Error: Status code $status_code"
-            exit 1
-          fi
+      # - name: "Consulta al endpoint"
+      #   shell: bash
+      #   run: |-
+      #     echo "${{ inputs.github_repository }}"
+      #     status_code=$(curl -o /dev/null -s -w "%{http_code}\n" --location --head "https://github-integration.andreani.com/api/v1/org/${{ inputs.github_repository_owner }}/repository/${{ inputs.github_repository }}")
+      #     if [ "$status_code" -eq 200 ]; then
+      #       echo "Successful request"
+      #     elif [ "$status_code" -eq 404 ]; then
+      #       echo "Error: Not found"
+      #       exit 1
+      #     else
+      #       echo "Error: Status code $status_code"
+      #       exit 1
+      #     fi
       - name: Esperar aprobación
-        if: ${{ failure() }}
+        # if: ${{ failure() }}
         uses: actions/github-script@v5
         with:
           script: |
