Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -11,4 +11,22 @@ runs:
   steps: 
       - name: Checkout
         uses: actions/checkout@v4
-
+      - name: "Consulta al endpoint"
+        env:
+          GITHUB_REPONAME: ${{ github.event.repository.name }}
+          GITHUB_OWNER: ${{ github.repository_owner }}
+        shell: bash 
+        run: |-
+          echo $GITHUB_REPONAME
+          echo $GITHUB_OWNER
+          
+          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" --location --head "${{ inputs.gitOpsUrl }}/api/v1/org/${{ env.GITHUB_OWNER }}/repository/${{ env.GITHUB_REPONAME }}")
+          if [ "$status_code" -eq 200 ]; then
+            echo "OK - The application is registered in GitOps"
+          elif [ "$status_code" -eq 404 ]; then
+            echo "Error: The application is not registered in GitOps. Send message to DevOps team"
+            exit 1
+          else
+            echo "Error: The GitOps response error -> $status_code"
+            exit 1
+          fi
