ci: migrate from actions

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,4 +1,5 @@
-name: 'Orleans helm package'
+name: 'Orleans build y push'
+
 inputs:
   ACR_USERNAME:
     description: "user de acr"
@@ -6,6 +7,10 @@ inputs:
     default: ''
   ACR_PASSWORD:
     description: "passwrd de acr"
+    required: true
+    default: ''
+  ACR_NAME:
+    description: "nommbre del acr"
     required: true
     default: ''
   ACR_FULL_NAME:
@@ -16,10 +21,6 @@ inputs:
     description: "Nombre de la aplicacion (dentro del proyecto)"
     required: true
     default: orleans-grain
-  namespace:
-    description: "nombre de namespaces"
-    required: false
-    default: ""
   teamProject:
     description: "Nombre del proyecto/equipo"
     required: true
@@ -28,54 +29,180 @@ inputs:
     description: "tag para subir imagen"
     required: true
     default: latest
+  ARGO_USERNAME:
+    description: "usuario de ARgocd"
+    required: true
+  ARGO_PASSWORD:
+    description: "pass de ARgocd"
+    required: true
+  ARGO_URL:
+    description: "url de ARgocd"
+    required: true
   helmChartVersionLatest:
-     description: "VersionHelm"
-     required: true
-  
+    description: "VersionHelm"
+    required: true
+  namespace:
+    description: "nombre de namespaces"
+    required: false
+    default: ""
+  environment:
+    description: "nombre de namespaces"
+    required: false
+    default: ""
+#env:
+  #Es un valor que viene del secreto, pero el install de helm lo espera cmo variable 'plana'
+#  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 runs:
   using: "composite"
   steps:
-      - run: echo 'Inicia el proceso'
+      - run: echo hi!, we working.
         shell: bash
-      
-      - name: Install Helm
-        uses: azure/setup-helm@v3
-        with:
-          version: v3.12.3 #Helm 13 tiene un bug
-      
-      - name: Reviso archivos y version helm
+      - run: ls
         shell: bash
-        run: |-
-           ls
-           helm version --short
+###REVISAR SI ESTO YA ESTA DE LA EJECUCION ANTERIOR
+
+      - name: Generate name
+        shell: bash
+        id: name
+        run: echo "applicationName=${{inputs.teamProject}}-${{inputs.appName}}-${{inputs.environment}}" >> $GITHUB_OUTPUT
 
       - uses: actions/download-artifact@v3
         with:
           name: ${{inputs.namespace}}
-    
-      - name: Helm Lint, verifica helm por errores (deberia ser bloqueante)
+          
+
+        # Se intenta 10 veces todos los pasos, con un sleep 20
+      - name: Login ArgoCD
         shell: bash
         run: |-
-          helmLint="helm lint --values=values.yaml > /dev/null 2>&1"
-          if eval "$helmLint"; then
-             echo "HELM Lint OK - The template folder and values file format is OK";
-          else
-             echo "HELM Lint FAIL - There is a problem with the folder 'templates' or the values file format";
-             exit 1
+          echo '${{ inputs.ACR_PASSWORD }}' | helm registry login ${{ inputs.ACR_FULL_NAME }} --username ${{ inputs.ACR_USERNAME }} --password-stdin
+          #cp poc-manifiestos-main/values.yaml .
+          #cp poc-manifiestos-main/Chart.yaml .
+          
+          echo 'login a argocd'
+          variableOk=0
+          argoCommand="argocd login --username ${{ inputs.ARGO_USERNAME }} --password ${{ inputs.ARGO_PASSWORD }} --insecure ${{ inputs.ARGO_URL }} --grpc-web"
+          for i in {1..10}
+          do
+          if eval "$argoCommand"; then
+              echo "ArgoCD login OK"
+              variableOk=1
+              break
+             else
+               echo "ArgoCD login $i/10"
+               sleep 20
+             fi
+          done
+          if [[ $variableOk != "1" ]]
+          then
+              echo "Error en ArgoCD Login" >&2;
+              exit 1
           fi
 
-      - name: Login to Azure Container Registry
-        uses: azure/docker-login@v1
-        with:
-          login-server: ${{ inputs.ACR_NAME }}.azurecr.io #ACR_FULL_NAME incluye el azurecr.io
-          username: ${{ inputs.ACR_USERNAME }}
-          password: ${{ inputs.ACR_PASSWORD }}
-      - name: Enpaquetar y subir helm a acr
+      - name: Create Project
         shell: bash
-        run: |-
-          export HELM_EXPERIMENTAL_OCI=1 #Es necesario para el chart save}}
-          helm package --version ${{ inputs.helmChartVersionLatest}} --app-version ${{ inputs.appVersion}} --namespace ${{ inputs.namespace}} .
-          echo '${{ inputs.ACR_PASSWORD }}' | helm registry login ${{ inputs.ACR_FULL_NAME}} --username ${{ inputs.ACR_USERNAME}} --password-stdin
-          helm push ${{inputs.TeamProject}}-${{inputs.appName }}-${{inputs.helmChartVersionLatest}}.tgz  oci://${{inputs.ACR_FULL_NAME }}/helm/ # ${{ inputs.TeamProject}}-${{ inputs.appName}}  # :${{ env.helmChartVersionLatest}}
+        run: |
+          echo 'creacion proyecto argocd'
+          variableOk=0
+          argoCommand="argocd proj create ${{inputs.namespace}} --upsert --dest https://kubernetes.default.svc,${{inputs.namespace}} --src  ${{ inputs.ACR_FULL_NAME }}/helm --grpc-web"
+          
+          for i in {1..10}
+          do
+          if eval "$argoCommand"; then
+              echo "ArgoCD Project create OK"
+              variableOk=1
+              break
+             else
+               echo "ArgoCD Project create $i/10"
+               sleep 20
+             fi
+          done
+          if [[ $variableOk != "1" ]]
+          then
+              echo "Error en ArgoCD Project create" >&2;
+              exit 1
+          fi
+      - name: creación app ArgoCD
+        shell: bash
+        run: |
+          echo 'creacion app argocd'
+          variableOk=0
+          argoCommand="argocd app create ${{ steps.name.outputs.applicationName }} --repo ${{ inputs.ACR_FULL_NAME }}/helm --helm-chart ${{inputs.teamProject}}-${{inputs.appName}} --upsert --helm-set Chart.yaml=Chart.yaml --helm-set-file values.yaml=values.yaml --helm-set-file Chart.yaml=Chart.yaml --revision ${{ inputs.helmChartVersionLatest}} --dest-namespace ${{inputs.namespace}} --dest-server https://kubernetes.default.svc --sync-policy auto --auto-prune --self-heal --project ${{inputs.namespace}} --grpc-web"
+          
+          for i in {1..10}
+          do
+          if eval "$argoCommand"; then
+              echo "ArgoCD app create OK"
+              variableOk=1
+              break
+             else
+               echo "ArgoCD app create $i/10"
+               sleep 20
+             fi
+          done
+          if [[ $variableOk != "1" ]]
+          then
+              echo "Error en ArgoCD app create" >&2;
+              exit 1
+          fi
+      - name: Wait Sync
+        shell: bash
+        run: |
+          #Wait. Espera la synchronizacion, esperan 30s, esperan 5 veces
+          # validar el nombre, antes tenia el -qa al final
+          argoWait="argocd app wait ${{ steps.name.outputs.applicationName }} --health --operation --timeout 30"
+          for i in {1..5}
+          do
+          if eval "$argoWait"; then
+                echo "ArgoCD app wait OK"
+                break
+            else
+                echo "ArgoCD app wait $i/5"
+                sleep 20
+            fi
+          done
+      - name: Clear cache
+        shell: bash
+        run: |
+          #Limpia cache de argocd - hard refresh
+          argocd app get ${{ steps.name.outputs.applicationName }} refresh --hard-refresh --grpc-web 2>&1
+          
+      - name: Sync
+        shell: bash
+        run: |
+          #Synch del repo (Fuerza el cambio de la aplicación a lo que se encuentra en los repos)
+          argoCommand="argocd app sync ${{ steps.name.outputs.applicationName }} --prune --force --retry-limit 5 --grpc-web --async"
+          variableOk=0
+          for i in {1..10}
+          do
+          if eval "$argoCommand"; then
+              echo "ArgoCD sync OK"
+              variableOk=1
+              break
+             else
+               echo "ArgoCD sync $i/10"
+               sleep 20
+             fi
+          done
+          if [[ $variableOk != "1" ]]
+          then
+              echo "Error en ArgoCD sync" >&2;
+              exit 1
+          fi
 
-           
+      - name: Wait Sync
+        shell: bash
+        run: |
+          #Wait. Espera la synchronizacion, esperan 30s, esperan 5 veces
+          argoWait="argocd app wait ${{ steps.name.outputs.applicationName }} --health --operation --timeout 30"
+          for i in {1..5}
+          do
+          if eval "$argoWait"; then
+                echo "ArgoCD app wait OK"
+                break
+            else
+                echo "ArgoCD app wait $i/5"
+                sleep 20
+            fi
+          done
+
